services:
  gym:
    build: .
    image: jcc-mashup:latest
    container_name: gym
    restart: unless-stopped
    ports:
      - "8001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
